# Symbolic Differentiation

```{r, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
# Load packages
library(mosaic)
library(mosaicCore)
library(mosaicCalc)
```

## Rundown

::: {.callout-note title="Learning goals"}
-   Coming Soon
:::

### Derivatives of Familiar Functions

#### Constant Rule

The derivative of a constant is 0. $$\frac{d}{dx}(c)= 0$$

#### Linear Function Rule

If $f(x)=mx+b$, then the derivative is the slope $m$. $$\frac{d}{dx}(mx+b)= m$$

#### Power Rule

$$\frac{d}{dx}(x^n)=n x^{n-1}$$

#### Trig Rules

$$\frac{d}{dx}\sin(x)=\cos(x)$$ and $$\frac{d}{dx}\cos(x)=-\sin(x)$$

#### Exponential Rules

$$\frac{d}{dx}(e^x)=e^x$$ and for any positive number $a >0$, $$\frac{d}{dx}(a^x)=(\ln a)a^x$$

#### Logarithmic Rules

$$\frac{d}{dx}(\ln (x))=\frac{1}{x}$$ and for any positive number $a >0$, $$\frac{d}{dx}(\log_a x)= \frac{1}{\ln (a)} \cdot \frac{1}{x}$$

### Arithmetic Rules for Derivatives

#### Constant Multiple Rule

If $c$ is a constant, then $$\frac{d}{dx}(cf(x))=c\frac{d}{dx}f(x)=cf'(x)$$

#### Sum and Difference Rules

$$\frac{d}{dx}(f(x)+g(x))=\frac{d}{dx}f(x)+\frac{d}{dx}g(x)=f'(x)+g'(x)$$ and $$\frac{d}{dx}(f(x)-g(x))=\frac{d}{dx}f(x)-\frac{d}{dx}g(x)=f'(x)-g'(x)$$

### Rules for Combinations of Functions

#### Product Rule

If $f(x)$ and $g(x)$ are functions then $$(fg)'=f'g+fg' \phantom{hihi} \text{ or } \phantom{hihi}(1st \cdot 2nd )'=D1st \cdot 2nd + 1st \cdot D2nd$$

#### Quotient Rule

If $f(x)$ and $g(x)$ are functions then $$\left(\frac{f}{g} \right ) '=\frac{gf'-fg'}{g^2} \phantom{hihi}\text{ or } \phantom{hihi}\left(\frac{hi}{lo} \right ) '=\frac{loDhi-hiDlo}{lo^2}$$

## Activities

### Basic Derivative Practice

Find the derivative for each of the following functions.

1.  $W(r) = r^3 + 5r - 12$
2.  $f(x) = x^2 - 3\ln x$
3.  $P(t) = 4t^2 + 7\sin t$
4.  $f(x) = 1/x^2 + 5\sqrt{x} - 7$
5.  $s(x) = 2e^{x} + x^2$
6.  $h(\theta) = 1/\sqrt[3]{\theta}$
7.  $b(t) = t^2 + 5\cos t$

### More Basic Derivative Practice

Find the derivative for each of the following functions.

1.  $g(x) = -\frac{1}{2}\left(x^5 +2x -9 \right)$
2.  $s(t) = 6t^{-2} + 3t^3 - 4t^{1/2}$
3.  $q(x) = 3x - 2\cdot 4^x$
4.  $y(x) = \sqrt{x}(x+1)$
5.  $P(t) = 3000(1.02)^t$
6.  $f(x) = 2^x + x^2 + 1$
7.  $d(r) = Ae^{r}  - Br^2 + C$
8.  $s(t) = t^2 + 2\ln t$
9.  $g(x) = 2x - \frac{1}{\sqrt[3]{x}} + 3^x - e$
10. $y(g) = 5\sin g - 5g + 4$

### Product Rule and Quotient Rule Practice

Find the derivative for each of the following functions.

1.  $s(t)=(t^2+4)(5t-1)$
2.  $y(x)=x^2\ln x$
3.  $g(x)= \frac{25x^2}{e^x}$
4.  $y(x)=x^2\cos x$
5.  $h(t)=\frac{t+4}{t-4}$

\
\
\
\

## Solutions

<details>

<summary>Click for Solutions</summary>

### Basic Derivative Practice

1.  $W'(r) = 3r^2 + 5$
2.  $f'(x) = 2x - 3/x$
3.  $P'(t) = 8t + 7\cos t$
4.  $f'(x) = -2x^{-3} + \frac{5}{2}x^{-1/2}$
5.  $s'(x) = 2e^{x} + 2x$
6.  $h'(\theta) = -\frac{1}{3}\theta^{-4/3}$
7.  $b'(t) = 2t - 5\sin t$

### More Basic Derivative Practice

1.  $g'(x) = -\frac{1}{2}(5x^4 + 2)$
2.  $s'(t) = -12 t^{-3} + 9t^2 -2t^{-1/2}$
3.  $q'(x) = 3 - 2\cdot \ln 4 \cdot 4^x$
4.  $y'(x) = \frac{3}{2}x^{1/2} + \frac{1}{2}x^{-1/2}$
5.  $P'(t) = 3000\cdot \ln 1.02 \cdot (1.02)^t$
6.  $f'(x) = \ln 2 \cdot 2^x + 2x$
7.  $d'(r) = Ae^{r} - 2Br$
8.  $s'(t) = 2t + 2/t$
9.  $g'(x) = 2 + \frac{1}{3}x^{-4/3} + \ln 3 \cdot 3^x$
10. $y'(g) = 5\cos g - 5$

### Product Rule and Quotient Rule Practice

1.  $s'(t) = 2t(5t-1) + (t^2+4)5$
2.  $y'(x) = 2x\ln x + x^2 \cdot 1/x$
3.  $f'(x) = 50xe^{-x} - 25x^2e^{-x}$
4.  $y'(x) = 2x\cos x - x^2\sin x$
5.  $h'(t) = \frac{(t-4) - (t+4)}{(t-4)^2}$

</details>
