project:
  type: book
  output-dir: docs


book:
  title: "Math 135: AMC I"
  author: "Macalester MSCS Faculty"
  date: "January 1, 2025"
  sidebar:
    collapse-level: 1
    pinned: true
    search: true
  chapters:
    - index.qmd
    - part: "Course Logistics"
      chapters:
      #- schedule.md
      - learning-goals.qmd
      #- homework.qmd
      #- syllabus.qmd
    - part: "Functions"
      chapters:
      - activities/1A-Functions.qmd
      - activities/1B-LinearFunctions.qmd
      - activities/1C-RateOfChange.qmd
      - activities/1D-ExpLog.qmd
      - activities/1E-Power.qmd
      - activities/1F-Periodic.qmd
      - activities/1G-Multivariable.qmd
      - activities/1Z-Summary.qmd
    - part: "Computational Derivatives"
      chapters:
      - activities/2A-DerivIntro.qmd
      - activities/2B-SecondDeriv.qmd         
      - activities/2C-PartialDeriv.qmd
      - activities/2D-Linearization.qmd
      - activities/2Z-Summary.qmd
    - part: "Symbolic Derivatives"
      chapters:
      - activities/3A-Differentiation.qmd
      - activities/3B-Chainrule.qmd         
      - activities/3C-PartialGradient.qmd
      - activities/3Z-Summary.qmd
    - part: "Optimization"
      chapters:
      - activities/4A-Optimization1D.qmd
      - activities/4B-Optimization2D.qmd 
      - activities/4C-GradientSearch.qmd 
      - activities/4D-ConstrainedOptimization.qmd 
      - activities/4Z-Summary.qmd 
    - part: "Integration"
      chapters:
      - activities/5A-AccumulatingChange.qmd
      - activities/5B-DefiniteIntegral.qmd
      - activities/5C-IndefiniteIntegral.qmd
      - activities/5Z-Summary.qmd
    - part: "Differential Equations"
      chapters:
      - activities/6A-DiffEq.qmd
      - activities/6B-PopModels.qmd
      - activities/6C-EulersMethod.qmd
      - activities/6D-SlopeFields.qmd
      - activities/6E-SpreadOfDisease.qmd
      - activities/6Z-Summary.qmd
      
  favicon: images/integral.png
  reader-mode: true
  site-url: https://mac-stat.github.io/COMPSTAT112



format:
  html:
    theme: united
    code-copy: true
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 150px

editor: visual

